import Head from "next/head";
import Image from "next/image";
import { useRef } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const divRef = useRef();
  console.log(divRef?.current?.offsetTop);

  return (
    <div className="flex h-[100vh] flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-1 justify-center">
        <div className="content-container flex flex-1 w-full max-w-md border-4">
          <div className="formulas-container flex">
            <span className="formula-shape w-14 bg-blue-500"></span>
          </div>
        </div>
      </main>
      <footer className="">only footer</footer>
    </div>
  );
}
